Question 1 :
Visit https://www.indeed.com/m/ website and search for Data Scientist in Los Angles. 
Now click on the “Find Jobs” button and you will be able to see the search results. 
Please find the top 200 jobs and obtain the frequencies of jobs that mention 
C, C++, Java, Javascript, Python, R, SQL, Hadoop, Hive, Pig, Spark, AWS and Tableau, respectively.

In [1]:
from bs4 import BeautifulSoup
import urllib
import re
import pandas as pd
import requests
from urllib.request import urlopen

In [2]:
title = []
company = []
location = []
jd = []
url = "https://www.indeed.com/m/jobs?q=data+scientist&l=Los+Angeles%2C+CA"
for i in range(20):
    
    page = urlopen(url)
    soup = BeautifulSoup(page, 'lxml')
    all_matches = soup.findAll(attrs={'rel':['nofollow']})
    for each in all_matches:
        jd_url= 'http://www.indeed.com/m/'+each['href']
        jd_page =urlopen(jd_url)
        jd_soup = BeautifulSoup(jd_page, 'lxml')
        jd_desc = jd_soup.findAll(attrs={'id':['desc']})
        title.append(jd_soup.body.p.b.font.text)
        company.append(jd_desc[0].span.text)
        location.append(jd_soup.body.p.span.text)
        jd.append(jd_desc[0].text)
        
    ## Change the pages to Next Page
    url_all = soup.findAll(attrs={'rel':['next']})
    url = 'http://www.indeed.com/m/'+ str(url_all[0]['href'])

In [3]:
job = {'Title': title,
         'Company': company,
         'Location': location,
         'Job Description': jd}
df = pd.DataFrame.from_dict(job)

In [4]:
df

,Title,Company,Location,Job Description
0,Data Scientist,Deloitte,"Los Angeles, CA 90013",Deloitte Services LP includes internal support...
1,Data Scientist,AvantStay,"Los Angeles, CA","Who we are...\nAvantStay delivers exceptional,..."
2,Data Scientist I - (Part-time),"Columbus Technologies and Services, Inc.","Pasadena, CA 91101",Must be a US Citizen\nEstimated duration of 12...
3,Data Scientist,Age of Learning,"Glendale, CA 91203",Company Overview:\nAge of Learning is a leadin...
4,Data Scientist,NBCUniversal,"Beverly Hills, CA","Fandango is seeking a driven, analytically cur..."
5,Data Scientist,GOAT,"Los Angeles, CA","With over 20 million members, GOAT is the worl..."
6,Data Scientist/Analyst,1 day ago,"Long Beach, CA",Required Qualifications-NLP exp must5-10 years...
7,Data Scientist,Niantic,"Culver City, CA",Do you want to help connect people all over th...
8,Data Scientist Population Health,"Martin Luther King, Jr. Community Hospital","Los Angeles, CA 90059",Under the guidance of the Manager of Data Scie...
9,Data Scientist,Cognizant,"Burbank, CA",We continuously seek exceptional associates wh...
10,Data Scientist (Analytics),Opendoor,"Los Angeles, CA","In 2014, we set out to reinvent life’s most im..."
11,Data Scientist Locals Only,12 days ago,"El Segundo, CA",Job SummaryTop Skills: Build AlgorithmsData Ac...
12,Data Scientist,VCA Animal Hospitals,"Santa Monica, CA",Data Scientist\nVCA IT Department seeks an exp...
13,Data Scientist,"Starz Entertainment, LLC","Los Angeles, CA",STARZ is looking for a skilled Data Scientist ...
14,Sales Operations Associate,Snapchat,"Los Angeles, CA",Snapchat is the camera used by millions of peo...
15,"Data Scientist, OCI",Oracle,"Culver City, CA","Data Scientist, OCI-19000T4C\n\n\nPreferred Qu..."
16,Statistician,SO CAL FCA BASEBALL,"La Mirada, CA 90638",All Intern Qualifications:\nRelationship with ...
17,Data Scientist - Legends of Runeterra,Riot Games,"Los Angeles, CA 90064","In 2009, Riot released its debut title League ..."
18,Data Scientist,L.A. Care Health Plan,"Los Angeles, CA 90017","Established in 1997, L.A. Care Health Plan is ..."
19,"Data Scientist, Modeling and Optimization - Ex...",California State University,"Dominguez, CA","Position Information\n\nThis is a full-time, p..."
20,Data Scientist,VideoAmp Careers Website,"Los Angeles, CA","About Us\n\nAt VideoAmp, we believe in challen..."
21,"Data Scientist, Snap Games",Snapchat,"Los Angeles, CA",We are looking for a Data Scientist with a dee...
22,Data Scientist,Roku,"Santa Monica, CA",Roku is looking for a Programming & Engagement...
23,Data Scientist,L.A. Care Health Plan,"Los Angeles, CA 90017","Established in 1997, L.A. Care Health Plan is ..."
24,"Data Scientist, Marketing Analytics",Kaiser Permanente,"Burbank, CA",Active participation in a range of market stra...
25,Data Scientist/Visualization Master,InterMedia Advertising,"Los Angeles, CA 90067",We are seeking a Manager of Business Intellige...
26,Data Scientist,UCLA Health,"Los Angeles, CA",Responsibilities\nThe Data Scientist is respon...
27,"Content Data Scientist, Apple Media Products D...",Apple,"Culver City, CA","Summary\nPosted: Aug 27, 2019\nRole Number: 20..."
28,Junior Data Scientist,Southern California Edison,"Rosemead, CA 91771",Job Description\nENERGY FOR WHAT’S AHEAD\nAre ...
29,Statistician,Phar LLC,"Beverly Hills, CA 90212",Data Analytics Team\nOverview of PHAR\nPartner...
...,...,...,...,...
170,Senior Data Scientist,Green Dot Corporation,"Pasadena, CA 91107",Job Type:\nRegular\nDepartment:\nBusiness Inte...
171,"Marketing Analyst, Analytics & Data Science",Assembly,"Los Angeles, CA",Data drives strategy. Assembly's Data Science ...
172,Data Engineer,Fox Corporation,"Los Angeles, CA 90036",OVERVIEW OF THE COMPANY\nFox Corporation\nUnde...
173,"Senior Data Scientist, Analytics",NEXT Trucking,"Los Angeles, CA",About NEXT:\n\nHeadquartered in “Silicon Beach...
174,"Product Manager, OCI - Data Science",Oracle,"Culver City, CA","Product Manager, OCI - Data Science-19000TFJ\n..."
175,Statistical Programmer,Murphy Research,"Santa Monica, CA 90401",Murphy Research is a full-service custom marke...
176,"Director, AI & ML Data Science",Warner Bros Careers,"Burbank, CA",Company Overview\nWarner Bros. has been entert...
177,Senior Data Analyst - Medical Care Solutions,Blue Shield of California,"Monterey Park, CA",GENERAL SUMMARY:\nUnder the direction of the S...
178,"Director, Data Science",BCGDV,"Manhattan Beach, CA",We're BCG Digital Ventures. Adventure awaits y...
179,"Artificial Intelligence, Consultant - Applied ...",Deloitte,"Los Angeles, CA 90013",Applied Artificial Intelligence - Artificial I...
180,"Data Analyst, Sr.","Honda R&D Americas, Inc.","Torrance, CA 90501",The Sr. Data Analyst is responsible for advanc...
181,Senior Data Analyst,Ventiv Technology,"Los Angeles, CA",SUMMARY:\nVentiv is seeking an experienced Dat...
182,Data Solutions Senior Analyst,Capital Group Companies,"Los Angeles, CA 90071",Req ID: 29880\nExperience Level: Professional\...
183,Advanced Category Management Data Scientist,Denso,"Long Beach, CA 90810",About DENSO\nDENSO is one of the largest globa...
184,Senior Data Analyst,PatientPop,"Santa Monica, CA 90401","At PatientPop, we believe healthcare providers..."
185,Senior Research Data Analyst,CBRE,"Los Angeles, CA",JOB SUMMARY\n\nCBRE is hiring a Senior Data An...
186,"Director, Data Science",Sony Pictures Entertainment Inc.,"Culver City, CA 90232","Director, Data Science\nDirector Data Science,..."
187,AI Engineer - Case Based Reasoning,Beyond Limits,"Glendale, CA",Position Overview:\nOur Artificial Intelligenc...
188,"Senior Analyst, Data Science",Roku,"Santa Monica, CA",The Role:\nRoku is looking for a Senior Analys...
189,Senior Data Analyst,iX.co,"Los Angeles, CA",This is a 6+ month contract role located in Lo...
190,Staff Machine Learning Engineer,Intuit,"Los Angeles, CA 90079","Overview\nIn this role, you’ll be embedded ins..."
191,Senior Marketing Data Analyst,Honey,"Los Angeles, CA 90067",Honey is a fast-growing startup based in Los A...
192,Lead Data Scientist,Zest Finance,"Los Angeles, CA",Lead Data Scientists lead Zest’s ML team to de...
193,Sr. Computer Vision Scientist,22 days ago,"Santa Monica, CA",SummaryOur Advertising Division engineering te...
194,"Machine Learning Engineer, AR/VR Discovery and...",Facebook,"Los Angeles, CA",The AR/VR team at Facebook is helping more peo...
195,Machine Learning Engineer,Oben,"Pasadena, CA",As a member of the machine language translatio...
196,Sr. Data Analyst,Honk,"Los Angeles, CA 90064",HONK is a fast growing technology company disr...
197,"VP, Data Science, Business Intelligence & Data...",NBCUniversal,"Universal City, CA",Role Summary:\nNBC Entertainment Digital is lo...
198,"Data Analyst - Health, Senior",Blue Shield of California,"Monterey Park, CA",GENERAL SUMMARY:\n\nWe are hiring for a Senior...
199,Senior Data Analyst,Honey,"Los Angeles, CA 90067",Honey is a fast-growing startup based in Los A...

In [41]:
description = pd.Series(jd)

mention_c = description.str.contains(r'\bC\b').sum()/200
mention_cplus = description.str.contains(r'\bC\+\+\b').sum()/200
mention_java = description.str.contains(r'\bJava\b').sum()/200
mention_javascript = description.str.contains(r'\bJavaScript\b').sum()/200
mention_python = description.str.contains(r'\bPython\b').sum()/200
mention_r = description.str.contains(r'\bR\b').sum()/200
mention_sql = description.str.contains(r'\bSQL\b').sum()/200
mention_hadoop = description.str.contains(r'\bHadoop\b').sum()/200
mention_hive = description.str.contains(r'\bHive\b').sum()/200
mention_pig = description.str.contains(r'\bPig\b').sum()/200
mention_spark = description.str.contains(r'\bSpark\b').sum()/200
mention_aws = (description.str.contains(r'\bAWS\b').sum()+description.str.contains(r'\bAmazon Web Services\b').sum())/200
mention_tableau = description.str.contains(r'\bTableau\b').sum()/200

In [42]:
tool = ['C', 'C++', 'Java', 'Javascript', 'Python', 'R', 'SQL', 'Hadoop',
        'Hive', 'Pig', 'Spark', 'AWS', 'Tableau']
frequency = [mention_c, mention_cplus, mention_java, mention_javascript, 
            mention_python, mention_r, mention_sql, mention_hadoop, mention_hive, 
            mention_pig, mention_spark, mention_aws, mention_tableau]
table = {'Tool' : tool, 'Frequency' : frequency}

df = pd.DataFrame.from_dict(table)
df

          Tool  Frequency
0            C      0.195
1          C++      0.025
2         Java      0.200
3   Javascript      0.000
4       Python      0.675
5            R      0.540
6          SQL      0.550
7       Hadoop      0.145
8         Hive      0.055
9          Pig      0.010
10       Spark      0.180
11         AWS      0.220
12     Tableau      0.255