Question 1 :
Visit https://www.indeed.com/m/ website and search for Data Scientist in Los Angles. 
Now click on the “Find Jobs” button and you will be able to see the search results. 
Please find the top 200 jobs and obtain the frequencies of jobs that mention 
C, C++, Java, Javascript, Python, R, SQL, Hadoop, Hive, Pig, Spark, AWS and Tableau, respectively.

In [2]:
from bs4 import BeautifulSoup
import urllib
import re
import pandas as pd
import requests
from urllib.request import urlopen

In [3]:
title = []
company = []
location = []
jd = []
url = "https://www.indeed.com/m/jobs?q=data+scientist&l=Los+Angeles%2C+CA"
for i in range(20):
    
    page = urlopen(url)
    soup = BeautifulSoup(page, 'lxml')
    all_matches = soup.findAll(attrs={'rel':['nofollow']})
    for each in all_matches:
        jd_url= 'http://www.indeed.com/m/'+each['href']
        jd_page =urlopen(jd_url)
        jd_soup = BeautifulSoup(jd_page, 'lxml')
        jd_desc = jd_soup.findAll(attrs={'id':['desc']})
        title.append(jd_soup.body.p.b.font.text)
        company.append(jd_desc[0].span.text)
        location.append(jd_soup.body.p.span.text)
        jd.append(jd_desc[0].text)
        
    ## Change the pages to Next Page
    url_all = soup.findAll(attrs={'rel':['next']})
    url = 'http://www.indeed.com/m/'+ str(url_all[0]['href'])

In [4]:
job = {'Title': title,
         'Company': company,
         'Location': location,
         'Job Description': jd}
df = pd.DataFrame.from_dict(job)

In [5]:
df

,Title,Company,Location,Job Description
0,Data Scientist,Deloitte,"Los Angeles, CA 90013",Deloitte Services LP includes internal support...
1,Data Scientist,AvantStay,"Los Angeles, CA","Who we are...\nAvantStay delivers exceptional,..."
2,Data Scientist I - (Part-time),"Columbus Technologies and Services, Inc.","Pasadena, CA 91101",Must be a US Citizen\nEstimated duration of 12...
3,Data Scientist/Visualization Master,InterMedia Advertising,"Los Angeles, CA 90067",We are seeking a Manager of Business Intellige...
4,Data Scientist,Age of Learning,"Glendale, CA 91203",Company Overview:\nAge of Learning is a leadin...
5,Data Scientist,30+ days ago,"Pasadena, CA 91101",Data ScientistQualificationsMajor in quantitat...
6,Data Scientist,GOAT,"Los Angeles, CA","With over 20 million members, GOAT is the worl..."
7,Data Scientist,NBCUniversal,"Beverly Hills, CA","Fandango is seeking a driven, analytically cur..."
8,Data Scientist/Analyst,2 days ago,"Long Beach, CA",Required Qualifications-NLP exp must5-10 years...
9,Data Scientist - Risk Management,LoanMart,"Van Nuys, CA 91406","ABOUT US: Wheels Financial Group, LLC d/b/a Lo..."
10,Data Scientist,13 hours ago,"Los Angeles, CA",Job Tittle : Data ScientistLocation : Los Ange...
11,Data Scientist Population Health,"Martin Luther King, Jr. Community Hospital","Los Angeles, CA 90059",Under the guidance of the Manager of Data Scie...
12,Data Scientist (Analytics),Opendoor,"Los Angeles, CA","In 2014, we set out to reinvent life’s most im..."
13,Data Scientist,Cognizant,"Burbank, CA",We continuously seek exceptional associates wh...
14,Data Scientist,VCA Animal Hospitals,"Santa Monica, CA",Data Scientist\nVCA IT Department seeks an exp...
15,Data Scientist,"Starz Entertainment, LLC","Los Angeles, CA",STARZ is looking for a skilled Data Scientist ...
16,Data Scientist Locals Only,13 days ago,"El Segundo, CA",Job SummaryTop Skills: Build AlgorithmsData Ac...
17,"Data Scientist, Modeling and Optimization - Ex...",California State University,"Dominguez, CA","Position Information\n\nThis is a full-time, p..."
18,Sales Operations Associate,Snapchat,"Los Angeles, CA",Snapchat is the camera used by millions of peo...
19,"Data Scientist, OCI",Oracle,"Culver City, CA","Data Scientist, OCI-19000T4C\n\n\nPreferred Qu..."
20,Sales Operations Associate,Snapchat,"Los Angeles, CA",Snapchat is the camera used by millions of peo...
21,"Data Scientist, Snap Games",Snapchat,"Los Angeles, CA",We are looking for a Data Scientist with a dee...
22,Data Scientist,"Starz Entertainment, LLC","Los Angeles, CA",STARZ is looking for a skilled Data Scientist ...
23,Data Scientist,Roku,"Santa Monica, CA",Roku is looking for a Programming & Engagement...
24,"Data Scientist, Modeling and Optimization - Ex...",California State University,"Dominguez, CA","Position Information\n\nThis is a full-time, p..."
25,Data Scientist - Machine Learning,Beyond Limits,"Glendale, CA",Job Title: Data Scientist - Machine Learning\n...
26,"Intern, Data Science (Summer 2020)",Ticketmaster,"Hollywood, CA 90028",Job Summary:\nWho we are\nWe’re fans who help ...
27,Data Scientist,L.A. Care Health Plan,"Los Angeles, CA 90017","Established in 1997, L.A. Care Health Plan is ..."
28,Data Scientist Locals Only,13 days ago,"El Segundo, CA",Job SummaryTop Skills: Build AlgorithmsData Ac...
29,Data Scientist,Deep 6 AI,"Pasadena, CA",Deep 6 AI is a fast-growing tech startup compa...
...,...,...,...,...
170,AI Engineer,Activision,"Woodland Hills, CA",Infinity Ward is currently seeking an AI Engin...
171,"Specialist SA, Machine Learning/AI Services",Amazon.com,"Santa Monica, CA","2+ years experience in the field of AI, Machin..."
172,Senior Data Scientist,Green Dot Corporation,"Pasadena, CA 91107",Job Type:\nRegular\nDepartment:\nBusiness Inte...
173,"Senior Data Scientist, Analytics",NEXT Trucking,"Los Angeles, CA",About NEXT:\n\nHeadquartered in “Silicon Beach...
174,"Marketing Analyst, Analytics & Data Science",Assembly,"Los Angeles, CA",Data drives strategy. Assembly's Data Science ...
175,Senior Data Services Engineer,Simply Hired,"Santa Monica, CA 90405",Retention Science is looking for an experience...
176,"Product Manager, OCI - Data Science",Oracle,"Culver City, CA","Product Manager, OCI - Data Science-19000TFJ\n..."
177,Statistical Programmer,Murphy Research,"Santa Monica, CA 90401",Murphy Research is a full-service custom marke...
178,Sr. Computer Vision Scientist,23 days ago,"Santa Monica, CA",SummaryOur Advertising Division engineering te...
179,"Director, AI & ML Data Science",Warner Bros Careers,"Burbank, CA",Company Overview\nWarner Bros. has been entert...
180,"Director, Data Science",BCGDV,"Manhattan Beach, CA",We're BCG Digital Ventures. Adventure awaits y...
181,"Data Analyst, Sr.","Honda R&D Americas, Inc.","Torrance, CA 90501",The Sr. Data Analyst is responsible for advanc...
182,Advanced Category Management Data Scientist,Denso,"Long Beach, CA 90810",About DENSO\nDENSO is one of the largest globa...
183,Senior Marketing Data Analyst,Honey,"Los Angeles, CA 90067",Honey is a fast-growing startup based in Los A...
184,Statistical Programmer,Murphy Research,"Santa Monica, CA 90401",Murphy Research is a full-service custom marke...
185,Senior Data Analyst,Ventiv Technology,"Los Angeles, CA",SUMMARY:\nVentiv is seeking an experienced Dat...
186,Senior Data Analyst,PatientPop,"Santa Monica, CA 90401","At PatientPop, we believe healthcare providers..."
187,"Director, Data Science",Sony Pictures Entertainment Inc.,"Culver City, CA 90232","Director Data Science, Audience Analytics and ..."
188,"Artificial Intelligence, Consultant - Applied ...",Deloitte,"Los Angeles, CA 90013",Applied Artificial Intelligence - Artificial I...
189,Senior Research Data Analyst,CBRE,"Los Angeles, CA",JOB SUMMARY\n\nCBRE is hiring a Senior Data An...
190,"Senior Analyst, Data Science",Roku,"Santa Monica, CA",The Role:\nRoku is looking for a Senior Analys...
191,Sr. Data Analyst,Honk,"Los Angeles, CA 90064",HONK is a fast growing technology company disr...
192,"VP, Data Science, Business Intelligence & Data...",NBCUniversal,"Universal City, CA",Role Summary:\nNBC Entertainment Digital is lo...
193,Data Solutions Senior Analyst,Capital Group Companies,"Los Angeles, CA 90071",Req ID: 29880\nExperience Level: Professional\...
194,AI Engineer - Case Based Reasoning,Beyond Limits,"Glendale, CA",Position Overview:\nOur Artificial Intelligenc...
195,"Data Analyst - Health, Senior",Blue Shield of California,"Monterey Park, CA",GENERAL SUMMARY:\n\nWe are hiring for a Senior...
196,Senior Data Analyst,Honey,"Los Angeles, CA 90067",Honey is a fast-growing startup based in Los A...
197,Senior Data Analyst,iX.co,"Los Angeles, CA",This is a 6+ month contract role located in Lo...
198,Computer vision and machine learning for Ocean...,Jet Propulsion Laboratory,"La Cañada Flintridge, CA 91011",Job Details\nJob ID: 10507\nNew ideas are all ...
199,Lead Data Scientist,Zest Finance,"Los Angeles, CA",Lead Data Scientists lead Zest’s ML team to de...

In [6]:
description = pd.Series(jd)

mention_c = description.str.contains(r'\bC\b').sum()/200
mention_cplus = description.str.contains(r'\bC\+\+\b').sum()/200
mention_java = description.str.contains(r'\bJava\b').sum()/200
mention_javascript = description.str.contains(r'\bJavaScript\b').sum()/200
mention_python = description.str.contains(r'\b[P|p]ython\b').sum()/200
mention_r = description.str.contains(r'\bR\b').sum()/200
mention_sql = description.str.contains(r'\bSQL\b').sum()/200
mention_hadoop = description.str.contains(r'\b[H|h]adoop\b').sum()/200
mention_hive = description.str.contains(r'\b[H|h]ive\b').sum()/200
mention_pig = description.str.contains(r'\b[P|p]ig\b').sum()/200
mention_spark = description.str.contains(r'\b[S|s]park\b').sum()/200
mention_aws = (description.str.contains(r'\bAWS\b').sum()+description.str.contains(r'\bAmazon Web Services\b').sum())/200
mention_tableau = description.str.contains(r'\b[T|t]ableau\b').sum()/200

In [7]:
tool = ['C', 'C++', 'Java', 'Javascript', 'Python', 'R', 'SQL', 'Hadoop',
        'Hive', 'Pig', 'Spark', 'AWS', 'Tableau']
frequency = [mention_c, mention_cplus, mention_java, mention_javascript, 
            mention_python, mention_r, mention_sql, mention_hadoop, mention_hive, 
            mention_pig, mention_spark, mention_aws, mention_tableau]
table = {'Tool' : tool, 'Frequency' : frequency}

df = pd.DataFrame.from_dict(table)
df

          Tool  Frequency
0            C      0.155
1          C++      0.010
2         Java      0.190
3   Javascript      0.000
4       Python      0.715
5            R      0.510
6          SQL      0.540
7       Hadoop      0.145
8         Hive      0.050
9          Pig      0.005
10       Spark      0.190
11         AWS      0.230
12     Tableau      0.250